# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Ben's awesome site
email: deleon010@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  This is my site to show of my javascript skills and use of jekyll
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: ben_deleon
github_username:  ben_deleon

# Build settings
markdown: kramdown
